#!/bin/sh
# invoke as $ concord file ... for a list words and the number of usages
#\
exec avram --parameterized "$0"  "$@"
sqZYqwI[ChA[\ByE`Cv_CNYAyskZf{JKK<<SXaXmOOQoOogAq@Xc=UYCVwxy^kWmo@KlLvO_?yOfX_o
azrxUVqAQ@EXPRhCIOIyx=jGog{HYwmoo{skJbRQWd{EyGpOUNxIVGEwwEnvGz?{\SkaJG{iQPp{?IP
Z{[putIJSKqs\>\KDVnAOwePYY@NBtvxn<ZDINJfGKwzGDvpfWkhngiANjkBKkn{BXxfzfO_y^fww\]
np_gZznKjlwNMTNFwkHphrqOOnLCjFsoZjkozWdDO=FWoFdab=J]H`O@yf{NiycKHgxXotFXhtfjT>P
`?>zvWkhqfsMbGFvxwDJv>=?jj{>ht>`O^eOZjMrgFDFw`GGr@`wb`utT<=C>zt?FsRV^YgdJXbggEX
sF=jz<RtNMjQfoBDgMRUA>MJNk\vJDVO^XrQHuAVv><OB_N>ZjT>XFHw_ex@ZvmRVQD@A>>R<p?eJ{Y
RM`to@LGN_\PEHuXocPMwan\<D\RwyVKzpO@t>\@PWcSH{aSD[jE`wnGdKKlhzBMJ<@wokpvxndyDSj
IwiH{`zoFi_dhMZ<QK\_oxOyFheWx?TZKjEJkHgo=Nj_aoA<z=bwKHnjOF_NQYqdLK]jxOhgrFgF><N
YX^K\YJGnQ`_Pv\H^v>K\ZuHtbF>`iJ{FK_`vfNOHHIH{\dz?wpd<<B>KKoDz?`thEJkH_TxaofHxoF
u=?\[jPOhgrDt\PW\kERNHEGHuHtbF>>ZvfNODbOpd<<cjG>mJd?w`e@tGw``WaOJ@ZuBO`ZuHO]ztU
@tSjmAtrCa<zLK^K^KfK^_wDzI_u=?ttzE?tlzhKaTz@LzXK]MzlCu>[\Ezb[\@Sf[\]zF[\mZ>[fAt
ezFAwEZBctPCvNS\UzBAtUzHAtuzE=ZRS`NZLklgl>j`dB<
